delete from ClienteEntity;
insert into ClienteEntity (id, nombre, direccion, correo) values (1, 'Andreana Cornilleau', '874 Glacier Hill Point', 'acornilleau0@economist.com');
insert into ClienteEntity (id, nombre, direccion, correo) values (2, 'Ardella Standbridge', '72 Buhler Junction', 'astandbridge1@clickbank.net');
insert into ClienteEntity (id, nombre, direccion, correo) values (3, 'Brynn Livingstone', '8 Gina Lane', 'blivingstone2@cornell.edu');
insert into ClienteEntity (id, nombre, direccion, correo) values (4, 'Latrina Brea', '4064 Reindahl Circle', 'lbrea3@bluehost.com');
insert into ClienteEntity (id, nombre, direccion, correo) values (5, 'Francesco Chidgey', '1 Packers Court', 'fchidgey4@cbslocal.com');
insert into ClienteEntity (id, nombre, direccion, correo) values (6, 'Melantha Berridge', '95003 Southridge Road', 'mberridge5@bizjournals.com');
insert into ClienteEntity (id, nombre, direccion, correo) values (7, 'Gavin Scarffe', '1173 Cody Parkway', 'gscarffe6@japanpost.jp');
insert into ClienteEntity (id, nombre, direccion, correo) values (8, 'Zorina Varian', '6229 Kennedy Lane', 'zvarian7@goodreads.com');
insert into ClienteEntity (id, nombre, direccion, correo) values (9, 'Gordie Marcus', '766 Continental Terrace', 'gmarcus8@photobucket.com');
insert into ClienteEntity (id, nombre, direccion, correo) values (10, 'Adriaens Holywell', '3 Barnett Point', 'aholywell9@wsj.com');
insert into ClienteEntity (id, nombre, direccion, correo) values (11, 'Lindsey Durran', '60 Leroy Junction', 'ldurrana@springer.com');
insert into ClienteEntity (id, nombre, direccion, correo) values (12, 'Zeke Karpeev', '0 Donald Lane', 'zkarpeevb@constantcontact.com');
insert into ClienteEntity (id, nombre, direccion, correo) values (13, 'Sascha Soall', '2 Arkansas Center', 'ssoallc@spiegel.de');
insert into ClienteEntity (id, nombre, direccion, correo) values (14, 'Ashien Assad', '86 Eastwood Way', 'aassadd@google.es');
insert into ClienteEntity (id, nombre, direccion, correo) values (15, 'Iorgos Chasen', '411 Nova Plaza', 'ichasene@bloglovin.com');
insert into ClienteEntity (id, nombre, direccion, correo) values (16, 'Cecil Djakovic', '781 Randy Junction', 'cdjakovicf@skyrock.com');
insert into ClienteEntity (id, nombre, direccion, correo) values (17, 'Tamma Struys', '46 Dottie Pass', 'tstruysg@statcounter.com');
insert into ClienteEntity (id, nombre, direccion, correo) values (18, 'Harli Earnshaw', '3349 Coolidge Street', 'hearnshawh@printfriendly.com');
insert into ClienteEntity (id, nombre, direccion, correo) values (19, 'Tildi Strangman', '0148 Sundown Alley', 'tstrangmani@washington.edu');
insert into ClienteEntity (id, nombre, direccion, correo) values (20, 'Iolande Ledamun', '366 Green Street', 'iledamunj@ca.gov');

delete from PRESTADORENTITY;
insert into PRESTADORENTITY (id, nombre, cedula) values (1, 'Tessi Perkins', 642702709);
insert into PRESTADORENTITY (id, nombre, cedula) values (2, 'Bambi Beswetherick', 591237150);
insert into PRESTADORENTITY (id, nombre, cedula) values (3, 'Tomasina Shiril', 569160688);
insert into PRESTADORENTITY (id, nombre, cedula) values (4, 'Adiana Turpin', 997948403);
insert into PRESTADORENTITY (id, nombre, cedula) values (5, 'Marjory Stent', 35727495);
insert into PRESTADORENTITY (id, nombre, cedula) values (6, 'Eziechiele Laity', 317414876);
insert into PRESTADORENTITY (id, nombre, cedula) values (7, 'Jonas Vaudre', 918011116);
insert into PRESTADORENTITY (id, nombre, cedula) values (8, 'Maxy Bremner', 654835077);
insert into PRESTADORENTITY (id, nombre, cedula) values (9, 'Nevsa Streight', 966207541);
insert into PRESTADORENTITY (id, nombre, cedula) values (10, 'Heloise McElvogue', 678621139);

delete from HABILIDADENTITY;
insert into HABILIDADENTITY (id, descripcion, tipo, prestador_id) values (1, 'Ut at dolor quis odio consequat varius.', 'faucibus', 1);
insert into HABILIDADENTITY (id, descripcion, tipo, prestador_id) values (2, 'Donec ut dolor.', 'convallis', 1);
insert into HABILIDADENTITY (id, descripcion, tipo, prestador_id) values (3, 'Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', 'scelerisque', 2);
insert into HABILIDADENTITY (id, descripcion, tipo, prestador_id) values (4, 'In congue.', 'dapibus', 2);
insert into HABILIDADENTITY (id, descripcion, tipo, prestador_id) values (5, 'Morbi non lectus.', 'lorem', 3);
insert into HABILIDADENTITY (id, descripcion, tipo, prestador_id) values (6, 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla.', 'vivamus', 3);
insert into HABILIDADENTITY (id, descripcion, tipo, prestador_id) values (7, 'Maecenas pulvinar lobortis est.', 'ipsum', 4);
insert into HABILIDADENTITY (id, descripcion, tipo, prestador_id) values (8, 'Curabitur gravida nisi at nibh.', 'in', 4);
insert into HABILIDADENTITY (id, descripcion, tipo, prestador_id) values (9, 'Praesent lectus.', 'gravida', 5);
insert into HABILIDADENTITY (id, descripcion, tipo, prestador_id) values (10, 'Suspendisse potenti.', 'vestibulum', 5);
insert into HABILIDADENTITY (id, descripcion, tipo, prestador_id) values (11, 'Phasellus in felis.', 'sem', 6);
insert into HABILIDADENTITY (id, descripcion, tipo, prestador_id) values (12, 'Pellentesque ultrices mattis odio.', 'quis', 6);
insert into HABILIDADENTITY (id, descripcion, tipo, prestador_id) values (13, 'Quisque id justo sit amet sapien dignissim vestibulum.', 'nunc', 7);
insert into HABILIDADENTITY (id, descripcion, tipo, prestador_id) values (14, 'Suspendisse potenti.', 'penatibus', 7);
insert into HABILIDADENTITY (id, descripcion, tipo, prestador_id) values (15, 'Etiam justo.', 'odio', 8);
insert into HABILIDADENTITY (id, descripcion, tipo, prestador_id) values (16, 'Curabitur convallis.', 'sem', 8);
insert into HABILIDADENTITY (id, descripcion, tipo, prestador_id) values (17, 'Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.', 'lacinia', 9);
insert into HABILIDADENTITY (id, descripcion, tipo, prestador_id) values (18, 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo.', 'porttitor', 9);
insert into HABILIDADENTITY (id, descripcion, tipo, prestador_id) values (19, 'Donec semper sapien a libero.', 'ultrices', 10);
insert into HABILIDADENTITY (id, descripcion, tipo, prestador_id) values (20, 'Duis consequat dui nec nisi volutpat eleifend.', 'ultrices', 10);

delete FROM SERVICIOENTITY;
delete FROM HojaDEVidaEntity;
delete FROM 