delete from ClienteEntity;
insert into ClienteEntity ( nombre, direccion, correo) values ('Andreana Cornilleau', '874 Glacier Hill Point', 'acornilleau0@economist.com');
insert into ClienteEntity ( nombre, direccion, correo) values ('Ardella Standbridge', '72 Buhler Junction', 'astandbridge1@clickbank.net');
insert into ClienteEntity ( nombre, direccion, correo) values ('Brynn Livingstone', '8 Gina Lane', 'blivingstone2@cornell.edu');
insert into ClienteEntity ( nombre, direccion, correo) values ('Latrina Brea', '4064 Reindahl Circle', 'lbrea3@bluehost.com');
insert into ClienteEntity ( nombre, direccion, correo) values ('Francesco Chidgey', '1 Packers Court', 'fchidgey4@cbslocal.com');
insert into ClienteEntity ( nombre, direccion, correo) values ('Melantha Berridge', '95003 Southridge Road', 'mberridge5@bizjournals.com');
insert into ClienteEntity ( nombre, direccion, correo) values ('Gavin Scarffe', '1173 Cody Parkway', 'gscarffe6@japanpost.jp');
insert into ClienteEntity ( nombre, direccion, correo) values ('Zorina Varian', '6229 Kennedy Lane', 'zvarian7@goodreads.com');
insert into ClienteEntity ( nombre, direccion, correo) values ('Gordie Marcus', '766 Continental Terrace', 'gmarcus8@photobucket.com');
insert into ClienteEntity ( nombre, direccion, correo) values ('Adriaens Holywell', '3 Barnett Point', 'aholywell9@wsj.com');
insert into ClienteEntity ( nombre, direccion, correo) values ('Lindsey Durran', '60 Leroy Junction', 'ldurrana@springer.com');
insert into ClienteEntity ( nombre, direccion, correo) values ('Zeke Karpeev', '0 Donald Lane', 'zkarpeevb@constantcontact.com');
insert into ClienteEntity ( nombre, direccion, correo) values ('Sascha Soall', '2 Arkansas Center', 'ssoallc@spiegel.de');
insert into ClienteEntity ( nombre, direccion, correo) values ('Ashien Assad', '86 Eastwood Way', 'aassadd@google.es');
insert into ClienteEntity ( nombre, direccion, correo) values ('Iorgos Chasen', '411 Nova Plaza', 'ichasene@bloglovin.com');
insert into ClienteEntity ( nombre, direccion, correo) values ('Cecil Djakovic', '781 Randy Junction', 'cdjakovicf@skyrock.com');
insert into ClienteEntity ( nombre, direccion, correo) values ('Tamma Struys', '46 Dottie Pass', 'tstruysg@statcounter.com');
insert into ClienteEntity ( nombre, direccion, correo) values ('Harli Earnshaw', '3349 Coolidge Street', 'hearnshawh@printfriendly.com');
insert into ClienteEntity ( nombre, direccion, correo) values ('Tildi Strangman', '0148 Sundown Alley', 'tstrangmani@washington.edu');
insert into ClienteEntity ( nombre, direccion, correo) values ('Iolande Ledamun', '366 Green Street', 'iledamunj@ca.gov');
