delete from ClienteEntity;
insert into ClienteEntity (id, nombre, direccion, correo) values (1, 'Andreana Cornilleau', '874 Glacier Hill Point', 'acornilleau0@economist.com');
insert into ClienteEntity (id, nombre, direccion, correo) values (2, 'Ardella Standbridge', '72 Buhler Junction', 'astandbridge1@clickbank.net');
insert into ClienteEntity (id, nombre, direccion, correo) values (3, 'Brynn Livingstone', '8 Gina Lane', 'blivingstone2@cornell.edu');
insert into ClienteEntity (id, nombre, direccion, correo) values (4, 'Latrina Brea', '4064 Reindahl Circle', 'lbrea3@bluehost.com');
insert into ClienteEntity (id, nombre, direccion, correo) values (5, 'Francesco Chidgey', '1 Packers Court', 'fchidgey4@cbslocal.com');
insert into ClienteEntity (id, nombre, direccion, correo) values (6, 'Melantha Berridge', '95003 Southridge Road', 'mberridge5@bizjournals.com');
insert into ClienteEntity (id, nombre, direccion, correo) values (7, 'Gavin Scarffe', '1173 Cody Parkway', 'gscarffe6@japanpost.jp');
insert into ClienteEntity (id, nombre, direccion, correo) values (8, 'Zorina Varian', '6229 Kennedy Lane', 'zvarian7@goodreads.com');
insert into ClienteEntity (id, nombre, direccion, correo) values (9, 'Gordie Marcus', '766 Continental Terrace', 'gmarcus8@photobucket.com');
insert into ClienteEntity (id, nombre, direccion, correo) values (10, 'Adriaens Holywell', '3 Barnett Point', 'aholywell9@wsj.com');
insert into ClienteEntity (id, nombre, direccion, correo) values (11, 'Lindsey Durran', '60 Leroy Junction', 'ldurrana@springer.com');
insert into ClienteEntity (id, nombre, direccion, correo) values (12, 'Zeke Karpeev', '0 Donald Lane', 'zkarpeevb@constantcontact.com');
insert into ClienteEntity (id, nombre, direccion, correo) values (13, 'Sascha Soall', '2 Arkansas Center', 'ssoallc@spiegel.de');
insert into ClienteEntity (id, nombre, direccion, correo) values (14, 'Ashien Assad', '86 Eastwood Way', 'aassadd@google.es');
insert into ClienteEntity (id, nombre, direccion, correo) values (15, 'Iorgos Chasen', '411 Nova Plaza', 'ichasene@bloglovin.com');
insert into ClienteEntity (id, nombre, direccion, correo) values (16, 'Cecil Djakovic', '781 Randy Junction', 'cdjakovicf@skyrock.com');
insert into ClienteEntity (id, nombre, direccion, correo) values (17, 'Tamma Struys', '46 Dottie Pass', 'tstruysg@statcounter.com');
insert into ClienteEntity (id, nombre, direccion, correo) values (18, 'Harli Earnshaw', '3349 Coolidge Street', 'hearnshawh@printfriendly.com');
insert into ClienteEntity (id, nombre, direccion, correo) values (19, 'Tildi Strangman', '0148 Sundown Alley', 'tstrangmani@washington.edu');
insert into ClienteEntity (id, nombre, direccion, correo) values (20, 'Iolande Ledamun', '366 Green Street', 'iledamunj@ca.gov');
